options:
  env:
    - "DOCKER_BUILDKIT=1"

steps:
- name: 'gcr.io/cloud-builders/docker'
  args: [
    'build',
    '-t', '${_IMAGE_NAME}',
    '.',
  ]
- name: 'gcr.io/cloud-builders/docker'
  args: [
    'push',
    '${_IMAGE_NAME}',
  ]

substitutions:
  _IMAGE_NAME: 'gcr.io/$PROJECT_ID/image'